### ISSUE TITLE
I can't successfully build the project "luisa-compute-rust-copy"

### ISSUE THREAD

**Issue by Liu-Wendao** [LuisaGroup/LuisaCompute#77] opened 2023-06-18 16:07 UTC
I want to build the projects "test_raytracing_weekend" and "test_swapchain". But when I build them, the compiler will report some errors on the project "luisa-compute-rust-copy". I can't successfully build the project "luisa-compute-rust-copy".

The errors are:
![QQ图片20230618235717](https://github.com/LuisaGroup/LuisaCompute/assets/83324034/fa96cf4a-1719-4a38-b14f-d40a45f542aa)

I use the Visual Studio 2022 to build these projects.

**Comment by Mike-Leo-Smith** [comment] 2023-06-18 16:32
Hi, @Liu-Wendao 

Would you please provide more details so that we can reproduce the error? For example, which commit is your cloned repo on? What options did you pass to CMake when configuring the project?

BTW, would you help check if the dependent targets (`cargo-build_luisa_compute_*`) are successfully built, and if the output directory (`D:/LuisaCompute/LuisaCompute/build/bin/Debug/../cargo/build/x86_64-pc-windows-msvc/debug/backend_support/`) exists? The Rust crates are possibly not successfully built due to network failure.

**Comment by Liu-Wendao** [comment] 2023-06-19 17:46
Which commit I clone was the latest commit on June 10, 2023. And the cmake command that I configure the project was "cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -D LUISA_COMPUTE_ENABLE_METAL=OFF -D LUISA_COMPUTE_ENABLE_CPU=OFF".

About the dependent targets (cargo-build_luisa_compute_*), I can successfully build these projects("cargo-build_luisa_compute_api_types", "cargo-build_luisa_compute_backend_impl" and "cargo-build_luisa_compute_ir") and output dll files. but the output directory(D:/LuisaCompute/LuisaCompute/build/bin/Debug/../cargo/build/x86_64-pc-windows-msvc/debug/backend_support/) doesn't exist.

In addition, some projects like "test_sdf_renderer", "test_shader_toy" and "test_swapchain", I can't successfully build them on vs2022 because of the project "luisa-compute-rust-copy". But they can still output the "exe" files, and I can test them using the arguments "cuda" and "dx" on windows 10 cmd. 

But when I run "test_raytracing_weekend.exe" using "dx",  cmd will report some error:
![Uploading error1.png…]()

But I can run "test_raytracing_weekend.exe" using "cuda".

**Comment by Liu-Wendao** [comment] 2023-06-19 17:50
@Mike-Leo-Smith 
Which commit I clone was the latest commit on June 10, 2023. And the cmake command that I configure the project was "cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -D LUISA_COMPUTE_ENABLE_METAL=OFF -D LUISA_COMPUTE_ENABLE_CPU=OFF".

About the dependent targets (cargo-build_luisa_compute_*), I can successfully build these projects("cargo-build_luisa_compute_api_types", "cargo-build_luisa_compute_backend_impl" and "cargo-build_luisa_compute_ir") and output dll files. but the output directory(D:/LuisaCompute/LuisaCompute/build/bin/Debug/../cargo/build/x86_64-pc-windows-msvc/debug/backend_support/) doesn't exist.

In addition, some projects like "test_sdf_renderer", "test_shader_toy" and "test_swapchain", I can't successfully build them on vs2022 because of the project "luisa-compute-rust-copy". But they can still output the "exe" files, and I can test them using the arguments "cuda" and "dx" on windows 10 cmd. 

But when I run "test_raytracing_weekend.exe" using "dx",  cmd will report some error:
![error1](https://github.com/LuisaGroup/LuisaCompute/assets/83324034/a132223a-e12d-447c-9cbb-b4adb08038a1)

But I can run "test_raytracing_weekend.exe" using "cuda".

**Comment by Mike-Leo-Smith** [comment] 2023-06-20 13:07
> Which commit I clone was the latest commit on June 10, 2023. And the cmake command that I configure the project was "cmake -S . -B build -D CMAKE_BUILD_TYPE=Debug -D LUISA_COMPUTE_ENABLE_METAL=OFF -D LUISA_COMPUTE_ENABLE_CPU=OFF".
> 
> About the dependent targets (cargo-build_luisa_compute_*), I can successfully build these projects("cargo-build_luisa_compute_api_types", "cargo-build_luisa_compute_backend_impl" and "cargo-build_luisa_compute_ir") and output dll files. but the output directory(D:/LuisaCompute/LuisaCompute/build/bin/Debug/../cargo/build/x86_64-pc-windows-msvc/debug/backend_support/) doesn't exist.

@Liu-Wendao Thanks for providing these important hints!

We have reproduced and tracked down the error. It's because when the CPU backend (implemented in Rust) is off, the `backend_support` directory would not be generated but the CMake script still wrongly tried to copy it when the remote backend is on.

I have pushed a patch in commit ff66c52 that fixes this issue. Please pull the repo and configure the project again.

> But when I run "test_raytracing_weekend.exe" using "dx", cmd will report some error:
> ![error1](https://user-images.githubusercontent.com/83324034/246899092-a132223a-e12d-447c-9cbb-b4adb08038a1.png)

Thanks for reporting this. There was a bug in detecting the texture alignment in the DirectX backend, which was recently fixed in commit 6dc6dd8 and a21bfc42f. Pulling the latest commit should also resolve this error.

**Closed as completed** 2023-07-18 18:25 UTC
